export const storePhones = [
    {
        id: 0,
        title: 'OPPO',
        img: 'img/oppo.png',
        price: 100.00,
        color: 'Black, Gold',
        screenSize: '5 inch',
        operatingSystem: 'Android',
        ram: '4GB',
        storage: '128GB',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 1,
        title: 'OPPO1',
        img: 'img/oppo.png',
        price: 1000.00,
        color: 'Black, Gold',
        screenSize: '5 inch',
        operatingSystem: 'Android',
        ram: '4GB',
        storage: '128GB',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: 'OPPO2',
        img: 'img/oppo.png',
        price: 2000.00,
        color: 'Black, Gold',
        screenSize: '5 inch',
        operatingSystem: 'Android',
        ram: '4GB',
        storage: '128GB',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: 'OPPO3',
        img: 'img/oppo.png',
        price: 3000.00,
        color: 'Black, Gold',
        screenSize: '5 inch',
        operatingSystem: 'Android',
        ram: '4GB',
        storage: '128GB',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: 'OPPO4',
        img: 'img/oppo.png',
        price: 4000.00,
        color: 'Black, Gold',
        screenSize: '5 inch',
        operatingSystem: 'Android',
        ram: '4GB',
        storage: '128GB',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: 'OPPO5',
        img: 'img/oppo.png',
        price: 5000.00,
        color: 'Black, Gold',
        screenSize: '5 inch',
        operatingSystem: 'Android',
        ram: '4GB',
        storage: '128GB',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: 'OPPO6',
        img: 'img/oppo.png',
        price: 6000.00,
        color: 'Black, Gold',
        screenSize: '5 inch',
        operatingSystem: 'Android',
        ram: '4GB',
        storage: '128GB',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        title: 'OPPO7',
        img: 'img/oppo.png',
        price: 7000.00,
        color: 'Black, Gold',
        screenSize: '5 inch',
        operatingSystem: 'Android',
        ram: '4GB',
        storage: '128GB',
        inCart: false,
        count: 0,
        total: 0
    },
];

export const detailsPhone = {
    id: 0,
    title: 'OPPO',
    img: 'img/oppo.png',
    price: 100.00,
    color: 'Black, Gold',
    screenSize: '5 inch',
    operatingSystem: 'Android',
    ram: '4GB',
    storage: '128GB',
    inCart: false,
    count: 0,
    total: 0
};